"""Offline churn and retrieval regression benchmarks for Steadlith chunking strategies.

The versioned fixtures provide fast, reproducible regression evidence. Run the
same APIs on a representative private corpus before making corpus-specific claims.
"""

from .churn import (
    DEFAULT_STRATEGY_NAMES,
    ILLUSTRATIVE_PRICE,
    Chunker,
    ChunkSnapshot,
    ChurnResult,
    ChurnSummary,
    EmbeddingPrice,
    benchmark_churn,
    default_strategies,
    measure_churn,
    measure_corpus_churn,
    snapshot_chunks,
    split_for_measurement,
)
from .corpora import (
    BUILTIN_CORPORA,
    BUILTIN_GOLD_QUESTIONS,
    BenchmarkDocument,
    CorpusFixture,
    CorpusKind,
    EditCase,
    EditOperation,
    GoldQuestion,
    apply_edit,
    get_corpus,
    iter_edit_cases,
    questions_for,
    validate_fixtures,
)
from .retrieval import (
    EmbeddingScorer,
    QuestionResult,
    RetrievalResult,
    RetrievalSummary,
    RetrievedChunk,
    ScoringMethod,
    benchmark_retrieval,
    evaluate_retrieval,
    hash_embedding_scores,
    lexical_scores,
    ndcg_at_10,
    ndcg_at_k,
    recall_at_k,
)

__all__ = [
    "BUILTIN_CORPORA",
    "BUILTIN_GOLD_QUESTIONS",
    "DEFAULT_STRATEGY_NAMES",
    "ILLUSTRATIVE_PRICE",
    "BenchmarkDocument",
    "ChunkSnapshot",
    "Chunker",
    "ChurnResult",
    "ChurnSummary",
    "CorpusFixture",
    "CorpusKind",
    "EditCase",
    "EditOperation",
    "EmbeddingPrice",
    "EmbeddingScorer",
    "GoldQuestion",
    "QuestionResult",
    "RetrievalResult",
    "RetrievalSummary",
    "RetrievedChunk",
    "ScoringMethod",
    "apply_edit",
    "benchmark_churn",
    "benchmark_retrieval",
    "default_strategies",
    "evaluate_retrieval",
    "get_corpus",
    "hash_embedding_scores",
    "iter_edit_cases",
    "lexical_scores",
    "measure_churn",
    "measure_corpus_churn",
    "ndcg_at_10",
    "ndcg_at_k",
    "questions_for",
    "recall_at_k",
    "snapshot_chunks",
    "split_for_measurement",
    "validate_fixtures",
]
